### ISSUE TITLE
Works with PHP 5.6, but not with PHP 7.0

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/psonesixmigrator#12]
Discussion: https://forum.thirtybees.com/topic/1719/impossible-to-make-the-migration-download-keeps-failing

A migration works fine with PHP 5.6, but throws errors with PHP 7.0. Logs are also available:

```
2018/05/07 07:24:54 [error] 3581#3581: *8323 FastCGI sent in stderr:
"PHP message: PHP Notice:  Trying to get property of non-object in /var/www/clients/client1/web10/web/modules/psonesixmigrator/classes/ObjectModel.php on line 170
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/clients/client1/web10/web/modules/psonesixmigrator/classes/ObjectModel.php on line 170"
while reading response header from upstream,
client: XX.XX.XX.XX,
server: XXXX.eu,
request: "POST /XXXX/autoupgrade/ajax-upgradetab.php HTTP/2.0",
upstream: "fastcgi://unix:/var/lib/php7.0-fpm/web10.sock:",
host: "www.XXXXX.eu",
referrer: "https://www.XXXXX.eu/XXXX/index.php?controller=AdminThirtyBeesMigrate&token=3ac0cdd5c5e19b17b026dd0e14c6d69f"
```
And this message appears, when the module reports the failure:
```
2018/05/07 07:25:59 [error] 3581#3581: *8323 FastCGI sent in stderr:
"PHP message: PHP Warning:  sprintf(): Too few arguments in /var/www/clients/client1/web10/web/modules/psonesixmigrator/classes/AjaxProcessor.php on line 307"
while reading response header from upstream,
client: XX.XX.XX.XX,
server: XXXXX.eu,
request: "POST /XXXX/autoupgrade/ajax-upgradetab.php HTTP/2.0",
upstream: "fastcgi://unix:/var/lib/php7.0-fpm/web10.sock:",
host: "www.XXXXX.eu",
referrer: "https://www.XXXXX.eu/adburma/index.php?controller=AdminThirtyBeesMigrate&token=3ac0cdd5c5e19b17b026dd0e14c6d69f"
```

**Comment by Traumflug** [comment]
This was solved somewhere between versions *1.0.0* and *1.0.2*.
